### ISSUE TITLE
Sequential creating error

### ISSUE THREAD

**Issue by shanepiesik** [statsmaths/kerasR#1]
When running

```
library(kerasR)
mod <- Sequential()
```
I get the following error: Error in Sequential() : attempt to apply non-function

**Comment by statsmaths** [comment]
It's likely that you do not have python or keras properly installed (this
does, I admit need a better error message). What happens when
you run the following?
```{r}
reticulate::py_available()
reticulate::import("keras.models")
```
If the first one fails, you likely do not have python installed. If the
second fails, you either do not have keras installed or you installed
it for a different version of python than R is finding. If its the
latter you can run
```{r}
reticulate::py_config()
```
To see exactly which version is loaded (potentially a problem
on macOS if you installed a different version from the default
system one).

**Comment by LarsSoto** [comment]
Many thanks for this package!

I'm experiencing the same issue as above. In my case, the second fails (as shown below). Question: How do I tell R to use a different version of python?

```r
reticulate::import("keras.models")
```
Error in py_module_import(module, convert = convert) : 
  ImportError: No module named keras.models

```r
reticulate::py_config()
```
python:         /usr/bin/python
libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
version:        2.7.10 (default, Jul 30 2016, 19:40:32)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
numpy:          /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy
numpy_version:  1.8.1

python versions found: 
 /usr/bin/python
 /usr/local/bin/python

## In shell

Leandros-MBP:~ lguelman$ python2
Python 2.7.13 (default, Jan 21 2017, 21:28:50) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
Using TensorFlow backend.

Thanks,
Lars.

**Comment by statsmaths** [comment]
Your system must be set up to make `python` point to "/usr/bin/python"
whereas `python2` points to "/usr/local/bin/python"; reticulate by default
is looking for the former but you've installed keras in the latter. It is a very
easy fix though. Just run this in R before loading anything else:
```{r}
library(reticulate)
use_python("/usr/local/bin/python")
```
You should then be able to run **kerasR** without a problem. If you run
into the same or different problems please let me know.

**Comment by LarsSoto** [comment]
Working perfect now! Thanks for your help!

L.

**Comment by hutaohutc** [comment]
I'm experiencing the same issue as above. I don't konw what can i do 
`reticulate::import("keras.models")`
Error in py_module_import(module, convert = convert) : 
  ValueError: Unknown backend: TensorFlow

Detailed traceback: 
  File "E:\Anaconda\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import activations
  File "E:\Anaconda\lib\site-packages\keras\activations.py", line 3, in <module>
    from . import backend as K
  File "E:\Anaconda\lib\site-packages\keras\backend\__init__.py", line 75, in <module>
    raise ValueError('Unknown backend: ' + str(_BACKEND))
`reticulate::py_config()`
python:         E:\Anaconda\python.exe
libpython:      E:/Anaconda/python27.dll
pythonhome:     E:\Anaconda
version:        2.7.9 |Anaconda 2.2.0 (64-bit)| (default, Dec 18 2014, 16:57:52) [MSC v.1500 64 bit (AMD64)]
Architecture:   64bit
numpy:          E:\Anaconda\lib\site-packages\numpy
numpy_version:  1.9.2

python versions found: 
 E:\Anaconda\python.exe
 D:\ANACON~1\python.exe

thanks for you times.

**Comment by statsmaths** [comment]
@hutaohutc Given that you are having an error just when importing keras.models, this looks like something wrong with you python setup. If you run this in Python does it give the same error?
```{py}
import keras.models
```
If that doesn't give an error there is some issue with which version of Python R is finding. If it does throw the same error, perhaps you never installed the python tensorflow package?

**Comment by datalee** [comment]
hello，when i run "import keras.models" in python:
(I:\Program Files\Anaconda2) C:\Users\topnet>python
Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import keras.models
Using Theano backend.

but,when i run "reticulate::import("keras.models")" in R:
> reticulate::import("keras.models")
Error in py_module_import(module, convert = convert) : 
  ValueError: Unknown backend: tensorflow

Detailed traceback: 
  File "I:\PROGRA~1\ANACON~1\lib\site-packages\keras-1.2.1-py2.7.egg\keras\__init__.py", line 2, in <module>
    from . import backend
  File "I:\PROGRA~1\ANACON~1\lib\site-packages\keras-1.2.1-py2.7.egg\keras\backend\__init__.py", line 66, in <module>
    raise ValueError('Unknown backend: ' + str(_BACKEND))

**Comment by NicolaDonelli** [comment]
Hi, I am working on macOS Sierra 10.12.4 and I am experiencing the same problem as shanepiesik.
I ran py_config() obtaining that I have two versions of python installed:

python versions found: 
 /usr/bin/python
 /Users/nicoladonelli/anaconda/bin/python

I know I have installed keras module on the anaconda version (already tried using Python) thus I tried to reach it using use_python("/Users/nicoladonelli/anaconda/bin/python") but somehow it didn't work (i.e. although py_available() returns TRUE, py_module_available("keras") returns FALSE and py_config() confirms that the system version of python is still used).
Any hint on how to solve this?

**Comment by NicolaDonelli** [comment]
Problem solved. 
I discovered that I cannot load more than one Python interpreter per session (maybe there should be a warning in reticulate... I'll tell them!) , and if I run py_config() before anything else it automatically load the first interpreter that it finds (which, obviously, is the wrong one!).
Thus the simple solution to my problem was to run use_python("PATH-TO-PYTHON") before py_config()

**Comment by statsmaths** [comment]
This issue should be fixed (or at least provided with workable warning messages) in version 0.5.0.

**Comment by WouterdH** [comment]
I'm not sure where I'm doing what wrongly?

> library(reticulate)
> library(kerasR)
> 
> use_python("/usr/local/bin/python3")
> py_config()
python:         /usr/bin/python
libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
version:        2.7.10 (default, Feb  6 2017, 23:53:20)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
numpy:          /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy
numpy_version:  1.8.1

python versions found: 
 /usr/bin/python
 /usr/local/bin/python3

**Comment by vamsiry** [comment]
Hi Iam also facing the same issue plz help
library(reticulate)
> use_python("C:\\Users\\vamsi\\Anaconda3\\envs\\py27\\python")
> library(kerasR)
> mod <- Sequential()
Error in Sequential() : attempt to apply non-function
> reticulate::py_available()
[1] TRUE
> reticulate::import("keras.models")
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'keras'
> reticulate::py_config()
python:         C:\Users\vamsi\ANACON~1\python.exe
libpython:      C:/Users/vamsi/ANACON~1/python36.dll
pythonhome:     C:\Users\vamsi\ANACON~1
version:        3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\vamsi\ANACON~1\lib\site-packages\numpy
numpy_version:  1.13.3

python versions found: 
 C:\Users\vamsi\ANACON~1\python.exe
 C:\Users\vamsi\Anaconda3\python.exe
 C:\Users\vamsi\Anaconda3\envs\Tensorflow\python.exe
 C:\Users\vamsi\Anaconda3\envs\py27\python.exe
> library(reticulate)
> use_python("C:\\Users\\vamsi\\Anaconda3\\envs\\py27\\python")
> library(kerasR)
> mod <- Sequential()
Error in Sequential() : attempt to apply non-function

**Comment by vamsiry** [comment]
Hi Iam also facing the same issue plz help
library(reticulate)
> use_python("C:\\Users\\vamsi\\Anaconda3\\envs\\py27\\python")
> library(kerasR)
> mod <- Sequential()
Error in Sequential() : attempt to apply non-function
> reticulate::py_available()
[1] TRUE
> reticulate::import("keras.models")
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'keras'
> reticulate::py_config()
python:         C:\Users\vamsi\ANACON~1\python.exe
libpython:      C:/Users/vamsi/ANACON~1/python36.dll
pythonhome:     C:\Users\vamsi\ANACON~1
version:        3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\vamsi\ANACON~1\lib\site-packages\numpy
numpy_version:  1.13.3

python versions found: 
 C:\Users\vamsi\ANACON~1\python.exe
 C:\Users\vamsi\Anaconda3\python.exe
 C:\Users\vamsi\Anaconda3\envs\Tensorflow\python.exe
 C:\Users\vamsi\Anaconda3\envs\py27\python.exe
> library(reticulate)
> use_python("C:\\Users\\vamsi\\Anaconda3\\envs\\py27\\python")
> library(kerasR)
> mod <- Sequential()
Error in Sequential() : attempt to apply non-function
