### ISSUE TITLE
Recurrent Layer Arguments

### ISSUE THREAD

**Issue by bradfox2** [statsmaths/kerasR#15]
Hi statsmath,

Really liking the package.  

I'm trying to implement stacked LSTM per keras docs: https://keras.io/layers/recurrent/.  The first LSTM call in a stacked configuration requires a 'return_sequences = True' argument when there is an LSTM layer following...  I.e. model.add(LSTM(64, input_dim=64, input_length=10, return_sequences=True))

Looking through the LSTM docs in kerasR and not seeing anything that would indicate this is an acceptable argument in the R LSTM call.

**Comment by statsmaths** [comment]
The current dev version of kerasR has a `return_sequences` option that you can set. Just make sure to specify the R version of boolean values (`TRUE` and `FALSE` rather than `True` and `False`).
