### ISSUE TITLE
can't use the Sequential()

### ISSUE THREAD

**Issue by AlexYoung757** [statsmaths/kerasR#16]
when i load the keras library, there has eroor as follows:
Error in Sequential() : attempt to apply non-function
 
i don't know why  my OS is win8.1 and the python version is 3.5.2

**Comment by hatemb** [comment]
Yes, I actually have the same issue. Could you solve it?

**Comment by AlexYoung757** [comment]
@hatemb i haven't solve this problem. maybe the python version is not compatible

**Comment by statsmaths** [comment]
This error probably means that you either (1) have an older version of kerasR or (2) are not successfully linking to Python or keras. Please download the most recent version of kerasR:
```{r}
devtools::install_github("statsmaths/kerasR")
```
And then see if kerasR can find your installation:
```{r}
kerasR::keras_available()
```
