### ISSUE TITLE
Can't Import keras

### ISSUE THREAD

**Issue by coreykimzey** [statsmaths/kerasR#18]
Hi, I'm kind of new to kerasR, so any help would be awesome. So when I try and run the code:
import("keras")
I get the following message:
Error in py_module_import(module, convert = convert) : 
  AttributeError: 'NoneType' object has no attribute 'write'

Detailed traceback: 
  File "...\ANACONDA3\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import activations
  File "...\ANACONDA3\lib\site-packages\keras\activations.py", line 4, in <module>
    from . import backend as K
  File "...\ANACONDA3\lib\site-packages\keras\backend\__init__.py", line 72, in <module>
    sys.stderr.write('Using TensorFlow backend.\n')
When I try import("tensorflow") , it comes out TRUE. Also when I try py_available("keras") it also comes out true. Any help would be awesome
Thanks

**Comment by statsmaths** [comment]
I'm a bit confused about your question. Are you using this package or just
calling Python directly with reticulate? It seems like the latter. In any case,
it seems that Python is not able to find keras; as explained in the reticulate
documentation `py_available` simple checks if Python is available on the
system. The argument you are passing it has no effect. The correct way
to check is with this following.
```
reticulate::py_module_available("keras")
```
Have you tried loading keras directly in Python?

**Comment by coreykimzey** [comment]
I'm using this package. I've been trying to fit a keras model, but I can't seem to get it to work. I did download keras directly into python.  When I do `reticulate::py_module_available("keras")` it comes out FALSE. 
I was trying to follow the example in the R documentation but every time I do:
`mod <- Sequential()`
I get the error:
Error in Sequential() : attempt to apply non-function

**Comment by statsmaths** [comment]
Okay, well if reticulate cannot find keras it makes sense that this is failing. So, what happens when you load keras within Python?

**Comment by coreykimzey** [comment]
In Python, I put:
'import keras'
I get back
'Using TensorFlow backend'
And that is it.

**Comment by jacekkotowski** [comment]
The same problem occurs to me:
I am using winpython 3.4 (I also tried the same with winpython 3.6
I can lodad keras in Python Spyder. 
I cannot load keras via reticulate or kerasR packages in RStudio.
I have described it in a thread on [stackoverflow](http://stackoverflow.com/questions/44071094/r-reticulate-package-does-not-see-keras-library-in-winpython)
the same as above with coreykimzey case.

**Comment by statsmaths** [comment]
So, there could be two things here. First of all, please download the most current version of kerasR from the repo:
```{r}
devtools::install_github("statsmaths/kerasR")
```
The issue mentioned on stackoverflow is likely a result of an earlier bug that has since been fixed.

However, I think the other issues is this: by default keras uses the tensorflow backend and when loading keras from R using reticulate whatever configuration file you have is not being read correctly. Keras then fails because it cannot find tensorflow. Is there any chance you could install the tensorflow Python package, at least to check if that is in fact the issue?

**Comment by coreykimzey** [comment]
Thanks statsmaths for all your help.  I tried both of those things. I already had the most recent version of kerasR. Also I tried installing tensorflow python package. It installed but I still am getting the same error in R.

**Comment by statsmaths** [comment]
Okay, so to recap you get FALSE when you run `py_module_available("keras")` but it runs fine when called from Python? I think the next thing to check is that you are linking the correct version of Python with reticulate. What is the output when you run `reticulate::py_config()`?

**Comment by coreykimzey** [comment]
Yes, it does work in python and I do get false for
py_module_available("keras"). Here is my output.
python:         C:\Users\KERRY_~1\python3\python.exe
libpython:      C:/Users/KERRY_~1/python3/python36.dll
pythonhome:     C:\Users\KERRY_~1\python3
version:        3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016,
11:57:41) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\KERRY_~1\python3\lib\site-packages\numpy
numpy_version:  1.11.3

**Comment by Luikigaba** [comment]
I have fixed it deleting from the ...\keras\backend\__init__.py file the line "sys.stderr.write('Using TensorFlow backend.\n')".

**Comment by coreykimzey** [comment]
Thanks that seemed to work!

**Comment by statsmaths** [comment]
@Luikigaba Ah okay, that is very strange that keras is writing to standard error about the backend (see here)[https://github.com/fchollet/keras/blob/master/keras/backend/__init__.py],

**Comment by statsmaths** [comment]
Actually, may have a possible solution to this now. Can you please download version 0.6.2 and retry?
```{r}
devtools::install_github("statsmaths/kerasR")
```

**Comment by silverstone1903** [comment]
Hi @statsmaths!

I've a similar problem. I can't import keras too. I'm using Anaconda2 and Anaconda3. TF and Keras are installed on Anaconda3 but when I check the py_config with reticulate it shows configuration for Python 2.7.13 (Anaconda2). I tried to change it with use_python command but it didn't work. Any idea? 

ps: I installed the latest version of kerasR (v 0.6.2)

**Comment by statsmaths** [comment]
@silverstone1903 Well, the issue is that you need to get `use_python` linked to the correct version of Python. What do you mean when you say that it doesn't work? Is there an error message?

**Comment by silverstone1903** [comment]
@statsmaths I coudn't explain it I guess. Like I said before I'm using Anaconda 2 and Anaconda 3. Keras is installed on Anaconda3. R uses Anaconda 2 by default. I want to change python, libpython and python home on reticulate with use_python command. even I can't change Python version so I don't know does package work or not :smiley:  Let me show you with ss:

![kerasr](https://cloud.githubusercontent.com/assets/9806827/26761406/09dfb7c8-4937-11e7-996e-638a2206ff33.JPG)

**Comment by statsmaths** [comment]
@silverstone1903 Thanks for the screenshot. Testing on my system, it seems like once python has been initialised you cannot change the version with `use_python`. Have you tried running the `use_python("C:/Program Files/Anaconda3/python.exe")` before anything else and seeing if that works?

**Comment by silverstone1903** [comment]
@statsmaths Yes I tried it but I don't remember clearly. Probably it worked with the older version of kerasR. Because once I tried kerasR package when you released it (a few months ago) then I didn't use again. You've updated package (also reticulate has been updated) and now it is not working for me. Btw I just wanted to ask if it's a common problem or something like that. It's not that important for me. I can use keras with anaconda3. Also problem is related about reticulate. So I don't want to take your time with this :disappointed:  Thank you for your interest!

**Comment by kdpsingh** [comment]
I'm having the same issue as @Luikigaba. keras working from Python 3.5 but not from R. I changed the ..\keras\backend_init_.py file to comment out the stderr.write function and now get the same error as described in post above.

**Comment by AlexYoung757** [comment]
i have the same issue as @coreykimzey . when i run py_module_available("keras") , it shows false. but when i  import keras for Pyhton ,it works well ,here is some config for my python
python:         D:\Anaconda\envs\tensorflow\python.exe
libpython:      D:/Anaconda/envs/tensorflow/python35.dll
pythonhome:     D:\Anaconda\envs\tensorflow
version:        3.5.3 |Continuum Analytics, Inc.| (default, Feb 22 2017, 21:28:42) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          D:\Anaconda\envs\tensorflow\lib\site-packages\numpy
numpy_version:  1.11.3

python versions found: 
 D:\Anaconda\envs\tensorflow\python.exe
 D:\Anaconda\python.exe
 D:\Anaconda/envs/tensorflow/python.exe

and  the kerasR is the newste version , how to solve this problem

**Comment by nishantsbi** [comment]
I have posted a solution to the issue which is similar to the thread here@ SO......have a look

https://stackoverflow.com/questions/44071094/r-reticulate-package-does-not-see-keras-library-in-winpython/45126846#45126846

**Comment by statsmaths** [comment]
I believe this was caused, at least in part, by the fact that numpy may need to be loaded before keras can be imported depending on your platform and Python version. @nishantsbi's solution is a good fall-back if the current dev version still does not fix the issue. Thanks for all the help!

**Comment by statsmaths** [comment]
@rachhitgarg Likely either you have pandas installed for a different version of Python or reticulate cannot find the library where the modules are stored. If you have more general **reticulate** questions I suggest posting on [the reticulate](https://github.com/rstudio/reticulate) page.
