### ISSUE TITLE
Failed to install kerasR - python not available & keras not available

### ISSUE THREAD

**Issue by chenhuiyou** [statsmaths/kerasR#20]
Hi, I have the same issue as the previous one. The problem might because of installing error of kerasR. 

I firstly set python path:
`> reticulate::use_python("C:/Anaconda3/envs/tensorflow/python.exe")`
`> reticulate::use_condaenv("C:/Anaconda3/envs/tensorflow")`
check python is available
`> reticulate::py_available()`
`[1] TRUE`

Then install "kerasR"
`> devtools::install_github("statsmaths/kerasR")`
gives out error:

> python not available
See reticulate::use_python() to set python path, 
then use kerasR::keras_init() to retry
*** arch - x64
|
keras not available
See reticulate::use_python() to set python path, 
then use kerasR::keras_init() to retry

Check modules of pyton:
`> reticulate::py_module_available("numpy")`
`[1] TRUE`
`> reticulate::py_module_available("scipy")`
`[1] TRUE`
`> reticulate::py_module_available("tensorflow")`
`[1] TRUE`
`> reticulate::py_module_available("keras")`
`[1] FALSE`

I am sure 'keras' is installed in python: 
`>>> import keras`
`Using TensorFlow backend.`

`> reticulate::py_config()`

> python:         C:/Anaconda3/envs/tensorflow/python.exe
> libpython:      C:/Anaconda3/envs/tensorflow/python35.dll
> pythonhome:     C:\ANACON~1\envs\TENSOR~1
> version:        3.5.3 |Continuum Analytics, Inc.| (default, May 15 2017, 10:43:23) [MSC v.1900 64 bit (AMD64)]
> Architecture:   64bit
> numpy:          C:\ANACON~1\envs\TENSOR~1\lib\site-packages\numpy
> numpy_version:  1.12.1
> numpy:          C:\ANACON~1\envs\TENSOR~1\lib\site-packages\numpy
> 
> python versions found: 
>  C:/Anaconda3/envs/tensorflow/python.exe
>  C:\ANACON~1\python.exe
>  C:\Anaconda\python.exe
>  C:\ANACON~1/envs/tensorflow/python.exe
>  C:\Anaconda/envs/tensorflow/python.exe

And my R version:

`> version`         
> platform       x86_64-w64-mingw32          
> arch           x86_64                      
> os             mingw32                     
> system         x86_64, mingw32             
> status                                     
> major          3                           
> minor          4.0                         
> year           2017                        
> month          04                          
> day            21                          
> svn rev        72570                       
> language       R                           
> version.string R version 3.4.0 (2017-04-21)
> nickname       You Stupid Darkness

**Comment by chenhuiyou** [comment]
> above

**Comment by statsmaths** [comment]
@chenhuiyou Thanks for the bug report. The fact that `reticulate::py_module_available("keras")` returns `FALSE` indicates that this is not something to do with the set up and not a bug in the **kerasR** package itself. 

When loading the **kerasR** package, you are getting a warning that python is not available even though when running `py_available` you get the result `TRUE`. One reason this could be is that we are calling `py_available` with `initalize = TRUE`, whereas the default is to not initialize. A good first step would be to run this:
```{r}
py_available(initialize = FALSE)
```
And see if that works.

**Comment by AlexYoung757** [comment]
hi @statsmaths  thank you for your help.
      i have installed the newest kerasR, but  when i use it  , such as : mod <- Sequential()  , the error is " Error in Sequential() : attempt to apply non-function" . so i use py_module_available("keras")  it shows false .
     when i use import("keras.models")  the error is as follow:
      Error in py_module_import(module, convert = convert) : 
     AttributeError: 'NoneType' object has no attribute 'write'

Detailed traceback: 
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import activations
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\keras\activations.py", line 4, in <module>
    from . import backend as K
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\keras\backend\__init__.py", line 72, in <module>
    sys.stderr.write('Using TensorFlow backend.\n')

 so what's the reason

**Comment by ErikVanem** [comment]
I had exactly the same problem, but found a away around it. It appears that there is a problem with the sys.stderr.write() in the _init_.py-file. By removing this line in the .pf-file it seems to work. 

In Python, sys.stderr.write() works, so I don't know why this does not work with kerasR in R. Can anyone explain why I get this error in the first place, and possibly fix this? Is it still a problem in kerasR since the sys.stderr.write function works in Python?

**Comment by statsmaths** [comment]
As explained in https://github.com/rstudio/reticulate/issues/65, I believe this has now been fixed.
