### ISSUE TITLE
What is the difference between this interface and the one from RStudio?

### ISSUE THREAD

**Issue by beeva-josealberto** [statsmaths/kerasR#22]
https://rstudio.github.io/keras/

Is there any substantial difference? Why not joining forces?

Thanks for the effort anyway. R needs this interface! :)

**Comment by statsmaths** [comment]
This one appeared publicly online and was even on CRAN several months before the RStudio one. Despite knowing of the project they never reached out and just decided to push their own software. I would certainly have preferred to coordinate, though RStudio seems more interested in *owning* all parts of the R ecosystem they can get their hands on.

In implementation, the RStudio package is better situated if you are R user wanting to build deep learning models in R. The interface is more R like, and there is less required set-up on your machine. The package here is for people that use Python or have significant Python code they want to port over to R; **kerasR** is a far more faithful wrapper to the Python library (functions are named the same; defaults are the same; options are all the same).
