### ISSUE TITLE
plot_model() requires dependencies in addition to Python pydot and graphviz

### ISSUE THREAD

**Issue by andrie** [statsmaths/kerasR#24]
The help for `plot_model()` says:

> This function requires that you have installed graphviz and pydot in Python.

And, indeed, I get an error message when running the code:

```r
library(kerasR)
mod <- Sequential()
mod$add(Dense(units = 50, input_shape = 13))
mod$add(Activation("relu"))
mod$add(Dense(units = 1))
plot_model(mod)
```

I get this error message:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ImportError: Failed to import pydot. You must install pydot and graphviz for `pydotprint` to work.

Detailed traceback: 
  File "/tensorflow/lib/python3.4/site-packages/keras/utils/vis_utils.py", line 131, in plot_model
    dot = model_to_dot(model, show_shapes, show_layer_names, rankdir)
  File "/tensorflow/lib/python3.4/site-packages/keras/utils/vis_utils.py", line 52, in model_to_dot
    _check_pydot()
  File "/tensorflow/lib/python3.4/site-packages/keras/utils/vis_utils.py", line 27, in _check_pydot
    raise ImportError('Failed to import pydot. You must install pydot'
```

The trouble is, these Python libraries are already installed:

```r
> library(reticulate)
> import("pydot")
Module(pydot)
> import("graphviz")
Module(graphviz)
```

**Comment by andrie** [comment]
The resolution is that the Python libraries are necessary, but insufficient.  You also need the `graphviz` binaries, and these are not installed with Python.

In Ubuntu you must do:

```bash
apt-get install -y graphviz libgraphviz-dev
```

For other operating systems, find the instructions at the [Graphviz website](http://www.graphviz.org/)

**Comment by dujintao** [comment]
in centos 6.5， you should run the command: sudo yum install graphviz libgraphviz-dev

**Comment by cserpell** [comment]
In Mac OS you can install it using `brew install graphviz`.

**Comment by logeshthamil** [comment]
In my case its not working even after installing graphviz and libgraphviz-dev.
OS version: Ubuntu 16.04
Error:   
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/vis_utils.py", line 131, in plot_model
    dot = model_to_dot(model, show_shapes, show_layer_names, rankdir)
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/vis_utils.py", line 52, in model_to_dot
    _check_pydot()
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/vis_utils.py", line 27, in _check_pydot
    raise ImportError('Failed to import pydot. You must install pydot'
ImportError: Failed to import pydot. You must install pydot and graphviz for `pydotprint` to work.

**Comment by vivekec** [comment]
https://stackoverflow.com/a/50025414/6126603
