### ISSUE TITLE
Enhance plot_model() to actually display the graph in R

### ISSUE THREAD

**Issue by andrie** [statsmaths/kerasR#25]
Suggestion: write a wrapper around `plot_model()` that reads the png from disk and plots it in the plot window in R, thus letting the function do what it says on the tin!

**Comment by andrie** [comment]
The code will look something like this:

```r
library(png)
library(grid)
library(ggplot2)
g <- rasterGrob(readPNG("model.png"))
ggplot() + 
  geom_blank() +
  annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
  geom_point()
```

**Comment by statsmaths** [comment]
This would be a nice functionality, but I'm trying to avoid having any more dependencies than necessary for the package. The **png** package is actually quite difficult to build from source in my experience and this could cause install issues for users trying to run **kerasR** on, for example, AWS or another minimal remote linux environment.
