### ISSUE TITLE
When will support CNTK backend?

### ISSUE THREAD

**Issue by strategist922** [statsmaths/kerasR#26]
Hi,
  May I know when will this package support CNTK backend?

thanks in advance!

**Comment by andrie** [comment]
CNTK version 2 has support for keras.

I haven't tried it, but I don't think this package needs modification to work with CNTK 2.

**Comment by statsmaths** [comment]
Yes, no modification needed. Just specify that you want that as a backend in the json object and it works fine as long as CNTK is set-up on your machine.
