### ISSUE TITLE
Cannot load boston data

### ISSUE THREAD

**Issue by smbatchou** [statsmaths/kerasR#27]
Hi,
I've been trying to load the boston dataset in my R session but the following error is returned:
> load_boston_housing()
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Exception: URL fetch failure on https://s3.amazonaws.com/keras-datasets/boston_housing.npz: None -- unknown url type: https

Detailed traceback: 
  File "/home/enigmatik/anaconda3/lib/python3.6/site-packages/keras/datasets/boston_housing.py", line 19, in load_data
    path = get_file(path, origin='https://s3.amazonaws.com/keras-datasets/boston_housing.npz')
  File "/home/enigmatik/anaconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 115, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))

### R session:
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /home/enigmatik/anaconda3/lib/libmkl_intel_lp64.so

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8    LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_0.7 kerasR_0.6.1  

loaded via a namespace (and not attached):
[1] compiler_3.4.0 R6_2.2.0       pbdZMQ_0.2-6   tools_3.4.0    Rcpp_0.12.10

**Comment by andrie** [comment]
My guess is that this is an issue with an older version of `reticulate`. 

I don't get this error with `reticulate_0.8`.

Please update `reticulate` and try again.

**Comment by mariobecerra** [comment]
I have `reticulate_1.4` and this happenned to me :/

**Comment by kwichmann** [comment]
I'm having the same problem as @mariobecerra

**Comment by mgei** [comment]
have you guys found a solution?

**Comment by mariobecerra** [comment]
I haven't. I used another computer and I was able to load it. Both computers had the same `reticulate` version, but I have no idea why it worked on one and not on the other.

**Comment by mgei** [comment]
I had the same issue. Solution for me was to first load it in Python. For this open Python in the correct environment (source activate r-tensorflow). Then load the data with this Python code

from keras.datasets import boston_housing
(x_train, y_train), (x_test, y_test) = boston_housing.load_data() 

If this gives no error it's fine. Then go back to R and try again with load_boston_housing(). Should load the pre-downloaded data and work fine.

**Comment by GreatEmerald** [comment]
Same issue here with the mnist dataset. The workaround by @mgei works, since that downloads the dataset from Python and caches it, so it's available from R as well.

**Comment by RumbleJack** [comment]
You should use 'http' instead of 'https'
