### ISSUE TITLE
use fit_generator

### ISSUE THREAD

**Issue by zaccliu** [statsmaths/kerasR#28]
Is there a concrete example of using fit_generator in kerasR? It requires to provide a generator and I don't know if it is possible to write a generator in R. Any suggestions would be appreciated.

**Comment by statsmaths** [comment]
No, not directly at the moment. We wanted to have complete coverage of the Python library so that is why this is included. You can construct native Python objects with **reticulate** and pass those to `fit_generator`, but at the moment that is the only way to use the generator function.
