### ISSUE TITLE
GRU and SimpleRNN return LSTM

### ISSUE THREAD

**Issue by Yannael** [statsmaths/kerasR#3]
Thanks for the great package!

It seems that in https://github.com/statsmaths/kerasR/blob/master/R/layers.recurrent.R, GRU and SimpleRNN return LSTM, why is that?

**Comment by statsmaths** [comment]
Glad you are enjoying the package. That was a just a (bad) typo. Just fixed in d611b2d881212519c75a2c8dbc9e37b3de82b0c1. Reinstalling with:
```{r}
devtools::install_github("statsmaths/kerasR")
```
Should fix it for you. Please file more issues if they come up. The package
is still very much in development.

**Comment by Yannael** [comment]
Great, thanks
