### ISSUE TITLE
Change signature for Sequential() to accept `...`

### ISSUE THREAD

**Issue by andrie** [statsmaths/kerasR#32]
Almost (all?) the documentation for `Sequential()` suggest to add layers as follows:

```r
mod <- Sequential()
mod$add(Dense(...))
mode$add(DropOut(...))
...
```

This multiple repetition of `mod$add()` is cumbersome and verbose.

You can already simplify this construct by passing a list of layers to `Sequential()`:

```r
mod <- Sequential(
  list(
    Dense(...),
    DropOut(...),
    ...
  )
)
```

I propose a small modification where instead of passing an explicit `list`, you simply pass multiple arguments, each a layer:

```r
mod <- Sequential(
    Dense(...),
    DropOut(...),
    ...
)
```

**Comment by statsmaths** [comment]
This is a non R-like way of passing arguments but I think for now I'd like to stay away from `...` arguments when they are not needed. Wrapping them in a `list` is not asking too much but can be essential in debugging issues both on our end and for users.
