### ISSUE TITLE
How to use class_weight, sample_weight parameters for imbalanced classes?

### ISSUE THREAD

**Issue by titubeta** [statsmaths/kerasR#33]
For training on imbalanced classes, class_weight or sample_weight parameters can be used. The documentation says that it should be class_weight should be a dictionary mapping and sample_weight parameter has to be numpy array. What will be the equivalent in R for both of these parameters?
What will be the exact syntax to use these parameters?

**Comment by titubeta** [comment]
it appears that using 'list' will work fine
`class_weight<-list(weight1,weight2)` 
Will the same 'list' idea work for sample_weight?

**Comment by statsmaths** [comment]
Yes, you can pass lists for both of these parameters or construct the native Python object with reticulate directly.

**Comment by dherrera1911** [comment]
I just stumbled into this problem. The list approach didn't work for sample_weight for me, but wsing a native Python object did work. For completeness and to aid other non-experts, the following code converts a weight vector in R into an object you can feed into sample_weight:

` np <- reticulate::import("numpy", convert=FALSE)`
`rWeiths <- c(0.5, 0.5, 0.5, 0.5, 1, 1)
`pyWeights <- np$array(reticulate::r_to_py(rWeights)`

Then just introduce pyWeights into sample_weights in keras_fit.
