### ISSUE TITLE
fails to detect keras although present

### ISSUE THREAD

**Issue by s-u** [statsmaths/kerasR#35]
kerasR will fails to detect keras:

```
> library(kerasR)
Using TensorFlow backend.

keras not available
```

due to

```
> reticulate::import("keras")
Error in py_module_import(module, convert = convert) : 
  ImportError: cannot import name np_utils
```

it appears to be a [known issue](https://stackoverflow.com/questions/45149341/importerror-cannot-import-name-np-utils) - `numpy` must be loaded first, so

```
> reticulate::import("numpy")
Module(numpy)
> library(kerasR)
Using TensorFlow backend.
successfully loaded keras
```

works.

**Comment by statsmaths** [comment]
That is a strange bug; I can't seem to replicate on my end. I thought the easy fix would be to just import numpy first, but that's already happening:

https://github.com/statsmaths/kerasR/blob/master/R/keras_init.R#L47-L50

Could you share your Python, kerasR, and reticulate versions so I can try to replicate (and then hopefully fix)?

**Comment by s-u** [comment]
The problem is that `keras_init` does NOT load numpy, because it fails in `keras_available` before it gets there. The issue is in `keras_available` which fails w/o numpy, not in `keras_init`.

It's a standard Ubuntu 16.04.2 LTS setup with system python 2.7.12, Keras 2.0.6, kerasR 0.8.0 (from GitHub the day I filed it), reticulate 1.0.0.9001

**Comment by statsmaths** [comment]
Ah, I mis-understood where the issue was happening. I added a line to load numpy first in the `keras_available` function. 

It still works on my system though without the change, but the last commit should fix the issue.

**Comment by s-u** [comment]
Yes, I can confirm that it fixes the issue. Thanks!
