### ISSUE TITLE
weights in an Embedding layer

### ISSUE THREAD

**Issue by mlampros** [statsmaths/kerasR#5]
Thank you for the useful package. I would like to reproduce the [pretrained_word_embeddings.py](https://github.com/fchollet/keras/blob/master/examples/pretrained_word_embeddings.py) example and use pre-trained word vectors in the Embedding layer. Is it possible with the kerasR package?

**Comment by statsmaths** [comment]
In general, you can replicate this example though of course it requires a lot of code to do so as all of the numpy steps would have to be converted over to R matrix methods. The specific step of setting Embedding weights can be done by calling the `add_weight` method after constructing the layer.
